name: test-prs
on:
  pull_request:

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: "Install: actions/checkout"
        uses: actions/checkout@v4

      - name: "Install: shfmt"
        uses: mfinelli/setup-shfmt@v3

      - name: "Check: shfmt"
        run: shfmt -d -i 2 -ci k

      - name: "Check: shellcheck"
        uses: sudo-bot/action-shellcheck@latest
        with:
            cli-args: k

      - name: "Install: bats‑core"
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.11.1

      - name: "Check: bats"
        run: bats -r tests

